### ISSUE TITLE
I can't use twig filter in my haml.blade

### ISSUE THREAD

**Issue by elyasaresya** [BKWLD/laravel-haml#23]
I'm using laravel 5, and this is my view (haml.blade)
`#{'Hello World' | lower}`

I try using {{ }} but the result is same.
`{{ 'Export Sales System' | lower  }}`

and the result is 

> Use of undefined constant lower - assumed 'lower'

**Comment by weotch** [comment]
This package doesn't work with Twig AFAIK.  Feel free to submit a PR that adds that support, though.  Shouldn't be tough to add, just add a config var for using php or twig and then invoke MtHAML differently depending on that selection: https://github.com/arnaud-lb/MtHaml#usage
