### ISSUE TITLE
Using haml + blade

### ISSUE THREAD

**Issue by pvos** [BKWLD/laravel-haml#5]
Implemented your code for haml views works great.
However I would like to combine the use of haml with the blade language.

Is there a workaround to combine and may I add this as a feature request?
If you can pinpoint me in right direction on how to achieve this, I can make a pull request also.

**Comment by weotch** [comment]
@trupedia can you let me know if that new commit on master works for your blade setup?

**Comment by weotch** [comment]
Also, you may note that you can use either `.blade.haml` or `.blade.haml.php` as your extension.

**Comment by trupedia** [comment]
@weotch Blade syntax works with the latest commit now as expected with your `.blade.haml` and `.blade.haml.php`extension, before they were registered as `.haml.blade`and `.haml.blade.php`.

**Comment by weotch** [comment]
Ok, gonna go ahead and tag the release
